language: c

matrix:
  include:
    - os: linux
      env:
        - PYTHON_VERSION=2.7
        - ANACONDA=https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
    - os: linux
      env:
        - PYTHON_VERSION=3.6
        - ANACONDA=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - os: osx
      env:
        - PYTHON_VERSION=2.7
        - ANACONDA=https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh
    - os: osx
      env:
        - PYTHON_VERSION=3.6
        - ANACONDA=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh

git:
  submodules: false

install:
  - wget "${ANACONDA}" -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels potassco/label/dev
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$PYTHON_VERSION
  - source activate test-environment
  - conda install -q clingo numpy
